image: aursu/rpmbuild:7.9.2009-docker

stages:
  - base
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  RL8: 8.10.20240528
  RL8TAG: 8.10.20240528
  RL9: 9.4.20240523
  RL9TAG: 9.4.20240523
  CI_COMMIT_SHORT_SHA_RL8: ${CI_COMMIT_SHORT_SHA}-rocky-8
  YUM0: rpmb.jfrog.io/artifactory/custom

rocky8base:
  stage: base
  variables:
    BASE: rocky8base
  script:
    - docker volume create $CI_COMMIT_SHORT_SHA_RL8
    - docker-compose -f docker-compose.base.yml build --no-cache --pull --build-arg repopath=$YUM0 $BASE

rocky8build:
  stage: build
  timeout: 12h
  variables:
    BUILD: rocky8build
  script:
    - docker-compose build --no-cache $BUILD
    - docker-compose run -v $CI_COMMIT_SHORT_SHA_RL8:/home/centos/rpmbuild/RPMS $BUILD

rocky8deploy:
  stage: deploy
  variables:
    FTPTRAY_USER: rocky-8
    FTPTRAY_REPO: gcc11custom
  script:
    - docker run --rm -v $CI_COMMIT_SHORT_SHA_RL8:/home/centos/rpmbuild/RPMS -e FTPTRAY_USER=$FTPTRAY_USER -e FTPTRAY_PASSWORD=$FTPTRAY_PASSWORD -e FTPTRAY_REPO=$FTPTRAY_REPO -e FTPTRAY_HOST=$FTPTRAY_HOST aursu/rpmbuild:ftptray /usr/local/bin/ftptray.py /home/centos/rpmbuild/RPMS
