version: "3"
services:
  centos7build:
    build:
      context: .
      args:
        os: $OS7
    command: ["-ba", "--with", "annobin-plugin-gcc"]
  rocky8build:
    build:
      context: .
      args:
        os: $RL8